name: Tim Nafziger
favicon: null
layout_spectrum: 1
typography_spectrum: 0.16451844340190291
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090907'
    - '#273d0f'
    - '#4d6b23'
    - '#979f4c'
    - '#723206'
  brandStrength: 0.19168018852360547
  lightness: 0.35229273955337703
  saturation: 0.25972301978617907
  rhythmicContrast: 0.9590233615599573
purpose: []
